dist: trusty

env:
  global:
  - secure: V7DAlRyGMI6Ix9zYshM3aaKG/mMcCCru5YJt8/0b4bftYKIsD+jm/1bWMaAjZlz3zsO+jc4/rv9VlDVfvVNpX8X1Ldp15imI6Xl4OYlpA8Sir1BYYsRwZ7JO9DtwL2mC5vhoeXWUNDZkFKt444ulwqyS6wJ+n0MxvtY0kBmA6SX8FIWo5tQ8cR50YOCpe4eBF2rk1/vrxppWzSjqY9GzV8ZmyOhNkxnGfpMcpolqiixJ04Ur06831zl2zLsH4IlTpnBD7gCklnRWUsvdvlXKiHVbY4ZDrr7tNPGRkr21hrC5cTyvE+W7BzS+En3RICufxvd1z7uRvbaLhKeOvI7yfY6WXl7eRaEuT8zKox90OG1uH3JH+92cAJ2uGVyKRT2P26rhX2DyjMBXbXRpLQGtRUgXTXJzgrjuSMR1qj861eWX1ntufxtoXIA5r3tTBVPTEKGeGUz6Qm88YSzN5Jgiors8k9iN1X+m8AQmpfGcLq7uk+MQwPlwaQ5xsXfJE63+0zMZbuPeBSEN5RIIKrXH+07YMDvuyUjyDDQ3FXKjLb/rMAhSc7gOSfazC6FDnMZyDCjFmrT+5xFUiY+S3Yy9ioG7EP/HcqeIyVlvf9cl4rJ2CtC4x3oy1OylCYcJC+6E0A0XzYMqp235dKpZG2Z0h4zoALhmcDy2XXhfahqWpQ8=
  - secure: W1dFhXXlCV0mzGvfPGcss8XFGsi1Ci29XURY+wHKca1c+7d8DG9Af8JbgccHBjtlz1pd5vIJtyIscx1BFcv+YNcrtcj4s5gK/pbMoiX2Z0dt/rqqFgVRZG5wuFVivq2xNKRfjeNHgUeS423rlneITHWZ6pAtNz2CZcn0mpRsgye3stP5ryEHNFMlwallLSU6y73Her8/cjofC6gogzriGv5rwhfQcp/jty3MolWkoIsIGp+KlHn/lPfALuVrEn2mg5tv4jRQQeJnIqOVNQACumEkC0LFgk/rtNEyR6wbZXVHmMNr9wgDl2OEtH78d2k57emi9lOh7pZVY68k7imhchkJEq5djaI2mGn1wdoHnPqQ78jLXftrNNUuhy9TYRscodOkZytVGQasQPvFWSMFHQrhmDvlNPEptpnc/pcatolGznN3V5w/SNS26urbL98vyJHNA8bfiTbMZKFoZraWYJ4BDEuQbV3gMe6Dy+8QF8p6NdsE8S8myb7cDj8d+4/W12y/z2m+b91SlJLqsHqP+lFfitC8lh7rFwPnqzHFxjXwdQ+bTUkXPsiJ/hMzUVA2hxk0c+Q9MPSJsVYUVnYNuromnYE0gKOt21YwS3QVKvU7F4/MD5+iybi2AGZipJJ8EWuQ6/S1pQYGkRMPxvJaOFvoPRTHCut6Vgum7GrecV8=

language: java

sudo: false

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.m2"

jdk:
- oraclejdk8

script:
- mvn clean install

after_success:
- "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings .travis/maven-settings.xml"
